# Generated by Django 4.2.7 on 2023-11-15 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=4)),
                ('fecha', models.DateField()),
                ('nombre_especialista', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener letras.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s]+$')])),
                ('diagnostico', models.TextField()),
                ('procedimiento', models.TextField()),
                ('tratamiento', models.TextField()),
                ('paciente_id', models.IntegerField()),
            ],
        ),
    ]
